####################################################################
#                        Prefix Settings                           #
####################################################################

prefix: $

####################################################################
#                       Extension Settings                         #
####################################################################

enabled_extensions: [vote]

####################################################################
#                        Token Settings                            #
####################################################################

# Uses the token stored in the .env file
# in the same directory as bot.py
token_env_enabled: true
token_env_key: DISCORD_TOKEN

# Only used if token_env_enabled is false
token: XXXYOURBOTTOKENHEREXXX
